# Generated by Django 4.2.25 on 2025-10-19 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['nome'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.DateTimeField(help_text='Quando acontecerá a consulta'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Informações extras do paciente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(help_text='Quem agendou a consulta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(help_text='Com qual médico', on_delete=django.db.models.deletion.CASCADE, to='core.profissional'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(help_text='Que tipo de consulta', on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('faltou', 'Paciente Faltou')], default='pendente', help_text='Situação atual do agendamento', max_length=10),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(help_text='Ex: Cardiologia, Dermatologia, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(db_index=True, help_text='Nome completo do profissional', max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, help_text='Detalhes sobre o serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(help_text='Quanto tempo dura o serviço (ex: 1h)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(help_text='Nome do serviço/consulta', max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Valor em reais', max_digits=8),
        ),
        migrations.AlterField(
            model_name='servico',
            name='profissional',
            field=models.ForeignKey(help_text='Profissional que oferece este serviço', on_delete=django.db.models.deletion.CASCADE, to='core.profissional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone do usuário', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('paciente', 'Paciente')], default='paciente', help_text='Define se é admin ou paciente', max_length=10),
        ),
    ]
